// Configuração das salas da igreja
export const salasOptions = [
  { value: '', label: 'Selecione um local' },
  { value: 'Templo', label: '🏛️ Templo' },
  { value: 'Anexo 1 - Salão', label: '🏢 Anexo 1 - Salão (Andar 0)' },
  { value: 'Anexo 1 - Sala 11', label: '🏢 Anexo 1 - Sala 11 (Andar 1)' },
  { value: 'Anexo 1 - Sala 12', label: '🏢 Anexo 1 - Sala 12 (Andar 1)' },
  { value: 'Anexo 1 - Biblioteca', label: '🏢 Anexo 1 - Biblioteca - Sala 15 (Andar 1)' },
  { value: 'Anexo 1 - Sala 16', label: '🏢 Anexo 1 - Sala 16 (Andar 1)' },
  { value: 'Anexo 1 - Sala 22', label: '🏢 Anexo 1 - Sala 22 (Andar 2)' },
  { value: 'Anexo 1 - Sala 23', label: '🏢 Anexo 1 - Sala 23 (Andar 2)' },
  { value: 'Anexo 1 - Sala 24', label: '🏢 Anexo 1 - Sala 24 (Andar 2)' },
  { value: 'Anexo 1 - Sala 26', label: '🏢 Anexo 1 - Sala 26 (Andar 2)' },
  { value: 'Anexo 1 - Sala 27', label: '🏢 Anexo 1 - Sala 27 (Andar 2)' },
  { value: 'Anexo 2 - Salão', label: '🏢 Anexo 2 - Salão (Andar 0)' },
  { value: 'Anexo 2 - Sala 11', label: '🏢 Anexo 2 - Sala 11 (Andar 1)' },
  { value: 'Anexo 2 - Sala 12', label: '🏢 Anexo 2 - Sala 12 (Andar 1)' },
  { value: 'Anexo 2 - Sala 13', label: '🏢 Anexo 2 - Sala 13 (Andar 1)' },
  { value: 'Anexo 2 - Sala 14', label: '🏢 Anexo 2 - Sala 14 (Andar 1)' },
  { value: 'Anexo 2 - Sala 15', label: '🏢 Anexo 2 - Sala 15 (Andar 1)' },
  { value: 'Anexo 2 - Sala 16', label: '🏢 Anexo 2 - Sala 16 (Andar 1)' },
  { value: 'Anexo 2 - Sala 17', label: '🏢 Anexo 2 - Sala 17 (Andar 1)' },
  { value: 'Anexo 2 - Sala 21', label: '🏢 Anexo 2 - Sala 21 (Andar 2)' },
  { value: 'Anexo 2 - Sala 22', label: '🏢 Anexo 2 - Sala 22 (Andar 2)' },
  { value: 'Anexo 2 - Sala 23', label: '🏢 Anexo 2 - Sala 23 (Andar 2)' },
  { value: 'Anexo 2 - Sala 24', label: '🏢 Anexo 2 - Sala 24 (Andar 2)' },
  { value: 'Anexo 2 - Sala 25', label: '🏢 Anexo 2 - Sala 25 (Andar 2)' },
  { value: 'Anexo 2 - Sala 26', label: '🏢 Anexo 2 - Sala 26 (Andar 2)' },
  { value: 'Anexo 2 - Sala 27', label: '🏢 Anexo 2 - Sala 27 (Andar 2)' },
  { value: 'Anexo 2 - Sala 31', label: '🏢 Anexo 2 - Sala 31 (Andar 3)' },
  { value: 'Anexo 2 - Sala 32', label: '🏢 Anexo 2 - Sala 32 (Andar 3)' },
  { value: 'Outro', label: '📍 Outro local' }
]; 